### ISSUE TITLE
Image position changing & Button short code not showing.

### ISSUE THREAD

**Issue by Dibbyo456** [better-studio/better-amp#17]
If I post a image in center position, in the amp version the image coming to the left, but it should be on center, does not it?
Also, the Shortcode buttons not showing in AMP.

**Comment by aliaghdam** [comment]
Hi @Dibbyo456 , 

Thanks for reporting. I will check the image issue and fix it. for the shortcodes i need your site link to check it.

<strong>Better</strong>Studio, Ali
