### ISSUE TITLE
Analytics can´t insert

### ISSUE THREAD

**Issue by Lofesa** [better-studio/better-amp#20]
Hi @aliaghdam 

If I put the analitics-id code in config, I get only this

`<amp-analytics type=googleanalytics> </amp-analytics>`

if leave blank the analytics-id code in the config not have these tags in html.

After digging in the issue, the plugins strip script tags, if I comment line 791 on file  better-amp/includes/classes/class-better-amp-content-sanitizer.php the google analytics code get printed.

**Comment by Lofesa** [comment]
Hi @aliaghdam 
..... and in footer.php you missed some ";"

```
"account": "<?php echo esc_attr( $ga_code ) ?>"

<?php endif ?>
```
lines 39 and 59

**Comment by aliaghdam** [comment]
Hi @Lofesa 
Thanks for reporting. 
This issue was updated with today update. (v1.1.2)
