### ISSUE TITLE
error gallery better amp

### ISSUE THREAD

**Issue by truongnb** [better-studio/better-amp#21]
Hello, I get the error does not show in the gallery interface amp. Specifically it only shows only one time with the first gallery, also from gallery 2 it does not show. If I delete the gallery 1 gallery 2 will be displayed.
ex: http://nhipsongso.net/amp/danh-gia-xe-hyundai-i20-active-hatchback-2017-xe-thanh-thi-thoi-trang-nho-gon/ (show gallery 1)
http://nhipsongso.net/danh-gia-xe-hyundai-elantra-2017-mau-xe-hang-c-tre-trung-tien-nghi-linh-hoat/ (not displayed)

**Comment by aliaghdam** [comment]
Hi @truongnb 
Thanks for reporting this issue.
I fixed it and it will be included in next public release.
Thanks
