### ISSUE TITLE
Templating

### ISSUE THREAD

**Issue by sopedro** [better-studio/better-amp#26]
Hi,

I tried to create  in my template folder /better-amp with all template files in there but changes doesn't take effect.
This plugin supports templating as AMP for wordpress ?

Thank you,

Pedro

**Comment by sopedro** [comment]
Anyone?

**Comment by Van-Halen** [comment]
Add this to your theme function file:

add_theme_support('better-amp-template');

**Comment by sopedro** [comment]
@Van-Halen Thank you.
