### ISSUE TITLE
How to Use Adsense on Better AMP?

### ISSUE THREAD

**Issue by 2besure** [better-studio/better-amp#27]
I love the plug-in.  The pages view beautifully.  Is there a way to use AdSense on Better AMP?  If so, how?

**Comment by aliaghdam** [comment]
Hi, 
BetterAds supports Google Adsense + Smart responsive Adsense, Google DFP + DFP smart spot detector, Banner Image and custom code ads and AdBlockers fallback ;)

We will publish the free version of BetterAds in next 3 weeks and you can get the BetterAds Pro version with purchasing our Publisher theme: https://themeforest.net/item/publisher/15801051
 


<strong>Better</strong>Studio, Ali
