### ISSUE TITLE
Breakdown of <head> tags on post pages

### ISSUE THREAD

**Issue by theanalystviews** [better-studio/better-amp#28]
Hi,

I previously used the official amp plugin on my website and it worked perfectly fine. however I decided to try the better-amp plugin due to its enhanced features.

better amp is working fine on the home page but there is a complete breakdown on <head>.....</head> on the post pages. please help me in resolving the problem.

my website: [www.theanalystviews.com](url)

Note: i'm using cloudflare. have set pagerules to allow amp.

**Comment by dimaslanjaka** [comment]
Me too.. I have same problem

**Comment by aliaghdam** [comment]
Hi
Thanks for reporting. That was an issue and was fixed in 418c1d120bc6d94e1b4d1ec51d88750456063f4e 
Please wait for coming update.
