### ISSUE TITLE
Image Bugs

### ISSUE THREAD

**Issue by akoda16** [better-studio/better-amp#29]
Hello good afternoon.

The plugin have a Bug that I need to fix urgently.

. The image exits the edges of the screen
. I need to change the typography of the title and the content
. I need to delete the content and leave the title of the entries on the pages

thank you very much for your help

PS: I attached the screenshot related to the bug image

<img width="1280" alt="screenshot 2017-04-18 20 41 29" src="https://cloud.githubusercontent.com/assets/27768709/25179752/794287f8-250b-11e7-9aa1-fae2e65ff1b3.png">

**Comment by aliaghdam** [comment]
Hi,

1. That will be fixed in coming update.
2. We will add that feature in future.
3. There is no option for that and you have to change codes!
