### ISSUE TITLE
no style on single post and pages

### ISSUE THREAD

**Issue by dimaslanjaka** [better-studio/better-amp#30]
A few minutes ago, iam install and activated this plugins. Everything is fine on homepage, archive, pagination, etc, BUT... On SINGLE PAGES And SINGLE POSTS Has NO STYLING . It output default text, nothing CSS outputed on source viewer. 

This my website... Https://l3n4r0x.cf

This Screenshot
![screenshot_2017-04-30-00-49-58](https://cloud.githubusercontent.com/assets/12471057/25557611/505f4812-2d3f-11e7-93ee-81c4f62703d9.jpg)

**Comment by kohaistyle** [comment]
We have the same issue. Works on home listing of post, but doesn't on single article or page.

Also, how does this plugin supports ads ?

Any help is appreciated, and congratulations for your work !

**Comment by gbaugher** [comment]
This worked for me.  Go to Apperance - Customize - AMP Theme - Posts.  In the Show share count? dropdown, select No. Don't Show.  This worked for me.

**Comment by aliaghdam** [comment]
This was a bug that was fixed in 418c1d120bc6d94e1b4d1ec51d88750456063f4e commit. Please wait for new update ;)
