### ISSUE TITLE
Short Codes

### ISSUE THREAD

**Issue by tejas511** [better-studio/better-amp#31]
Hello,
We are using shortcodes of ContactForm7 for some pages. Due tho this our forms are not displayed on AMP pages. Can you suggest some solution?

**Comment by aliaghdam** [comment]
Hi,
Forms are very restricted in AMP and you have to create them manualy to make sure it works! BetterAMP removes invalid codes (from CF7) plugin to make sure your site will be valid.

Generally, AMP was not created to show contact form and collecting data!
