### ISSUE TITLE
Custom AMP CSS doesn't override normalize

### ISSUE THREAD

**Issue by faia20** [better-studio/better-amp#33]
Hi there.
Thanks for the great plugin. I've tested some amp plugins and this one is definitely the best for me!
I'm using better-amp with the publisher theme.
The button styles that I added to the additional css under the Better AMP plugin it's not overriding other styles because this css is being inputed before other styles. The amp css should be inputed after any other css including normalize css.
Please have a look at www.bestdroidplayer.co.uk/amp/xbmc-android-tv-box-droidplayer/best-xbmc-apps-addons-for-your-android-tv-box/ and open the source code.

**Comment by aliaghdam** [comment]
Thanks for reporting and kind words. It will be fixed in coming update.
