### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by motwguy** [better-studio/better-amp#34]
I (and several others) are getting  this message:

Fatal error: Call to undefined function bf_social_share_guss_current_page() in /home/motwguy/marketing-ontheweb.com/wp-content/plugins/better-amp/includes/functions/theme-functions.php on line 2469

I have systematically deactivated all my plug-ins to no avail. 

also see: https://wordpress.org/support/topic/fatal-error-2583/

**Comment by galbaras** [comment]
In includes/functions/theme-functions.php, line 2469 should be changed from

`$current_page = bf_social_share_guss_current_page();`

to

`$current_page = better_amp_social_share_guss_current_page();`

Line 2476 should also be changed from:

`count_number = bf_social_share_fetch_count( $site_id, $current_page['page_permalink'] );`

to

`$count_number = better_amp_social_share_fetch_count( $site_id, $current_page['page_permalink'] );`

**Comment by motwguy** [comment]
Thank you. Will this be corrected in the next update?

**Comment by aliaghdam** [comment]
@galbaras Thanks for information and help.

@motwguy Yes this will be included in coming update ;)
