### ISSUE TITLE
Social sharing box configuration for posts not working

### ISSUE THREAD

**Issue by galbaras** [better-studio/better-amp#35]
In the customizer, in the Posts area, when I change the selection of social networks, the "save" button doesn't change. If I make other changes and save them, social network selections remain unchanged.

Also, although the cursor changes to a cross over the social networks, they cannot be reordered.

**Comment by aliaghdam** [comment]
As I checked it works properly. Please check all active plugins and deactivate them to find the problem. I think it's a javascript issue from one of your active your plugins.
