### ISSUE TITLE
Feature Request: Ads Management 

### ISSUE THREAD

**Issue by aliaghdam** [better-studio/better-amp#6]
Option to add:

- Ads by Google Adsense and other popular sites
- Custom IMG and HTML banner ads

Ad Locations:
- Before post title
- After post thumbnail
- After post thumbnail
- Between specific posts in archive pages (ex. 5 post)  
- Option to add Ads between specific paragraph (ex. after 5th paragraph)
- Footer ads

**Please post +1 if you are interested.**

**Comment by Dibbyo456** [comment]
God knows, if they ever going to implement it

**Comment by aliaghdam** [comment]
Hi @Dibbyo456 , 

Sure, This is under progress and will be added in v1.2 of BetterAMP But we decided to add it to our Better Ads Manager plugin that is complete solution for Ads management. 
BetterAds was included in our themes for free but can be purchased separately.

I will update this ticket with news.

<strong>Better</strong>Studio, Ali

**Comment by aliaghdam** [comment]
Ads functionality added in 713909e and 76e404f

This functionality is depended to our **Better Ads** plugin. Currenlty you can access that plugin with purchasing our theme https://themeforest.net/item/publisher/15801051 

We will sell **Better Ads** in future and if you haven't purchased our theme you can buy **Better Ads** directly from us with sending email to info@betterstudio.com
