### ISSUE TITLE
AMP Page always displaying the homepage

### ISSUE THREAD

**Issue by dabeeyow** [better-studio/better-amp#61]
Hi Admin,

Please refer to the sample page below.

https://www.tataydigong.info/amp/bir-allows-collection-offices-to-accept-one-time-transactions/

Thanks!

**Comment by dabeeyow** [comment]
Hi Admin,

I have just updated to version 1.9.4 but the issue still exists.

https://www.tataydigong.info/amp/aerosmiths-perry-cancels-tour-after-recent-hospital-visit/

Thanks!

**Comment by aliaghdam** [comment]
Hi
Please update to latest version. This issue was fixed in v1.9.4
