### ISSUE TITLE
Feature Request: Redirect Mobile visitors to AMP version

### ISSUE THREAD

**Issue by aliaghdam** [better-studio/better-amp#7]
Option to make sure all mobile visitors will redirector to AMP version of site (the exact page in AMP version) automatically.

This can be done simply but the main problem is compatibility with caching plugins that didn't enables this! Please give me a solution if you know that!

**Please post +1 if you are interested.**

**Comment by chatingtou** [comment]
+1

**Comment by Dibbyo456** [comment]
I was also thinking about that + ads management for AMP

**Comment by aliaghdam** [comment]
@Dibbyo456 The main problem is the cache plugins! bebause they are chaching pages as normal and there is no any chance to redirect user to none mobile version!

Currently @abolfazl-moeini is working on this and it will be available in comming days ;)

**Comment by chatingtou** [comment]
Hi Ali

Thanks, looking forward to the new version

Ricky

**Comment by chatingtou** [comment]
Why the light box not works in my site as the posts are imported from blogspot. I have already turned on the light box.
http://reaydepart.ga

Thanks
Ricky

**Comment by aliaghdam** [comment]
Hi @chatingtou 
Please create new issue for your problem.

P.s. It seams your link is not correct or your domain was expired!

**Comment by aliaghdam** [comment]
Update:

@abolfazl-moeini is working on this in new branch
https://github.com/better-studio/better-amp/tree/mobile-auto-redirect

**Comment by aliaghdam** [comment]
Finished in 48937b8d96ca81fe9a248b0b40be53cb268b97bb commit
